---
version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - './app:/code/app'
    networks:
     - app

networks:
  app:
    driver: bridge
