#!/usr/bin/env bash

# it's really annoying to do `docker-compose exec app` all the time when you just want to test a quick thing
# created this script to make my life a bit easier and added some handy utils here as well

dc() {
  docker-compose "$@"
}

case "$1" in
  "up" | "down")
    dc "$@";;
  "tinker")
    dc exec app python;;
  *)
    dc exec app "$@";;
esac

