name: Quality checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: python:3.10.3-slim
    services:
      postgres:
        image: postgres:13.6-alpine
        env:
          POSTGRES_USER: "movielist"
          POSTGRES_PASSWORD: "movielist"
          POSTGRES_DB: "movielist"
    steps:
      - uses: actions/checkout@v2
      - name: Install system dependecies
        run: |
          apt update && \
          apt install -y gcc
      - name: Install pip dependencies
        run: pip install -r requirements-dev.txt
      - name: Run database migratiosn
        run: alembic upgrade head
      - name: Run tests
        run: pytest
